apiVersion: configmanagement.gke.io/v1
kind: ClusterSelector
metadata:
  name: application-selector
spec:
  selector:
    matchLabels:
      environment: dev
      type: application
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
data:
  MAX_NODES: "4"
  MONITORING_ENABLED: "true"
