apiVersion: v1
kind: Namespace
metadata:
  name: test
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: james-session

