apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: apigroups-must-have-gk
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace", "Deployment", "Pod", "ReplicaSet"]
  parameters:
    labels: ["gatekeeper"]
